
CREATE SCHEMA `intertecintl` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE `intertecintl`.`username` (
  `USER_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`USER_ID`));
  

CREATE TABLE `intertecintl`.`word` (
  `WORD_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `WORD_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`WORD_ID`));

SET SQL_SAFE_UPDATES = 0;

COMMIT;